name: Deploy Olympiad Laravel to Hostinger

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy changed files by FTP
        uses: SamKirkland/FTP-Deploy-Action@v4.4.0
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./
          server-dir: ./
          dangerous-clean-slate: false
          exclude: |
            **/.git*
            **/.git*/**
            **/.github/**
            **/.env
            **/.env.*
            **/node_modules/**
            laravel/.env
            laravel/storage/**
            laravel/bootstrap/cache/*.php
            **/*.sql
            **/*.sql.gz
            **/*.zip
            **/*.tar
            **/*.tar.gz
            **/composer-setup.php
            **/composer.phar

            laravel/vendor/**
            laravel/vendor/**/*
            laravel/storage/logs/**
            laravel/storage/logs/**/*
            laravel/storage/framework/cache/**
            laravel/storage/framework/cache/**/*
            laravel/storage/framework/sessions/**
            laravel/storage/framework/sessions/**/*
            laravel/storage/framework/views/**
            laravel/storage/framework/views/**/*
